---
# ansible-playbook -v 001.requirements.yml -u root
- name: "Installing required ansible galaxy packages"
  gather_facts: no
  hosts: localhost
  become: no
  tasks:
    - name: "Install Ansible roles for GlusterFS"
      shell: "ls -lah ~/.ansible/"
      register: output
      
    - name: "Install Ansible roles for GlusterFS"
      shell: "ansible-galaxy install -r requirements.yml --output-path /var/lib/awx/.ansible/"
      register: output

    - debug:
        var: output
        
    - name: "Installing Jmespath through pip3"
      pip:
        name: jmespath
        state: present
        executable: pip3
