---
# ansible-playbook -v 003.setup_glusterfs_cluster.yml -u root
- hosts: all
  become: yes
  become_user: root
  gather_facts: True

  # Install glusterfs-server before running the tasks of
  # gluster.cluster role
  pre_tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: http://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/rsa.pub
        state: present
      when: ansible_os_family == 'Debian'
    
    - name: Add an RPM signing key, uses whichever key is at the URL
      rpm_key:
        key: http://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/rsa.pub
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Add new apt source
      apt_repository:
        repo: deb https://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/LATEST/Debian/stretch/amd64/apt stretch main
        filename: gluster.list
        state: present
      when: ansible_os_family == 'Debian'
    
    - name: Add yum apt source
      yum_repository:
        name: glusterfs
        description: glusterfs YUM repo
        baseurl: https://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/LATEST/RHEL/glusterfs-rhel8.repo
      when: ansible_os_family == 'RedHat'

    - name: Update repositories cache and install "glusterfs-server" package
      package:
        name: glusterfs-server
        update_cache: yes

    - name: Set python path symlink
      file:
        src: "/usr/bin/python3.7"
        dest: "/usr/bin/python"
        state: link
      when: ansible_os_family == 'RedHat'
  
  vars:
    glusterd_version: '7'

    # gluster volume
    gluster_cluster_hosts: "{{ glusterfs_cluster_ips.split(',') }}"
    # gluster volume
    gluster_cluster_volume: 'gv0'
    gluster_cluster_transport: 'tcp'
    gluster_cluster_force: 'yes'
    gluster_cluster_bricks: '/mnt/brick1'

    # variables to create specific type of the volume
    #gluster_cluster_replica_count: '2'

    # variables to set specific volume options
    # gluster_cluster_options: 'performance.cache-size:256MB'

  roles:
     - gluster.cluster